#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

sudo apt-get update -y
sudo apt install -y haproxy

# configure haproxy
echo "
frontend idkmal-tech-frontend
    bind *:80
    default_backend idkmal-tech-backend
    timeout client 30s

backend idkmal-tech-backend
    balance roundrobin
    server 498908-web-01 54.90.10.167:80 check
    server 498908-web-02 34.232.67.169:80 check
    timeout connect 5s
    timeout server 30s
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# restart proxy
sudo service haproxy restart