#!/bin/bash

# Create an RSA key pair with a private key named "school" and a bit size of 4096
openssl genrsa -out school -aes256 -passout pass:betty 4096

# Extract the public key from the private key
openssl rsa -pubout -in school -out school.pub -passin pass:betty